export const skillsList = {
  1: "Web Development",
  2: "Machine Learning",
  3: "Artificial Intelligence",
  4: "Data Science",
  5: "Data Analytics",
  6: "Internet of Things",
  7: "Automation",
  8: "Embedded System",
  9: "Robotics",
  10: "Physics",
  11: "Chemistry",
  12: "Crafts & Arts",
  13: "Literature",
  14: "Automobiles & Services",
  15: "Yoga",
  16: "Sports",
  17: "Dance",
  18: "Music",
  19: "Cinematic Skills",
  20: "Athletics",
};
