export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_DETAILS_REQUEST = "USER_REGISTER_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_DETAILS_FAIL = "USER_REGISTER_FAIL";
export const USER_DETAILS_RESET = "USER_REGISTER_RESET";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_RESET = "USER_LIST_RESET";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
export const USER_UPDATE_RESET = "USER_UPDATE_RESET";

export const USER_REQUEST_REQUEST = "USER_REQUEST_REQUEST";
export const USER_REQUEST_SUCCESS = "USER_REQUEST_SUCCESS";
export const USER_REQUEST_FAIL = "USER_REQUEST_FAIL";

export const USER_ACCEPT_REQUEST = "USER_ACCEPT_REQUEST";
export const USER_ACCEPT_SUCCESS = "USER_ACCEPT_SUCCESS";
export const USER_ACCEPT_FAIL = "USER_ACCEPT_FAIL";

export const USER_UNREQUEST_REQUEST = "USER_UNREQUEST_REQUEST";
export const USER_UNREQUEST_SUCCESS = "USER_UNREQUEST_SUCCESS";
export const USER_UNREQUEST_FAIL = "USER_UNREQUEST_FAIL";

export const USER_DECLINE_REQUEST = "USER_DECLINE_REQUEST";
export const USER_DECLINE_SUCCESS = "USER_DECLINE_SUCCESS";
export const USER_DECLINE_FAIL = "USER_DECLINE_FAIL";

export const USER_DEVELOPER_REQUEST = "USER_DEVELOPER_REQUEST";
export const USER_DEVELOPER_SUCCESS = "USER_DEVELOPER_SUCCESS";
export const USER_DEVELOPER_FAIL = "USER_DEVELOPER_FAIL";
